### ISSUE TITLE
Refatorar o código

### ISSUE THREAD

**Issue by DaltonDam** [DaltonDam/Cinevault#1]
Refatoramente e correções de código

**Comment by isaiasgh** [comment]
Oi, vi que o issue #1 é sobre refatoração e correções de código. Poderia me dar mais detalhes sobre o que exatamente precisa ser feito? Se for possível, gostaria de me envolver nesse task e se puder, me assigna ele, ficaria feliz em ajudar! 😊

**Comment by DaltonDam** [comment]
Boa tarde, o código já foi refatorado. Utilizo o postman para testar a API, eram alguns erros no POST que tava retornando como nulo, mesmo atualizando com sucesso os atributos no GET

**Comment by isaiasgh** [comment]
Entendido, obrigado pela resposta! Se surgir algum outro issue no futuro, ficaria feliz em ajudar
